# keep in sync with urlfetch_tree_SOURCE_CODE_APP_ID in appengine_config.py
application: try-appengine
version: bliss
runtime: python27
api_version: 1
# Mimic target environment is not yet threadsafe
threadsafe: false

includes:
- codemirror.yaml
- bliss.yaml
- tasks.yaml

# https://developers.google.com/appengine/docs/python/config/appconfig#Builtin_Handlers
builtins:
- admin_redirect: on
- appstats: on
- deferred: on
- remote_api: on

# Currently supported inbound services are documented by
# https://developers.google.com/appengine/docs/python/config/appconfig#Inbound_Services
inbound_services:
- channel_presence
- mail
- xmpp_message
- xmpp_presence
- xmpp_subscribe
- warmup

handlers:
- url: /_ah/mimic/version_id
  # The version id handler should probably just be split off into its own
  # script. This handler doesn't require user login because client apps will
  # want to know if this is a mimic and its version.
  script: mimic.app

# script handler for everything else / user code
- url: /.*
  # This module must be removed from sys.modules in TargetEnvironment.RunScript
  script: mimic.app
  # This script handler must either not require login, or require admin login
  # (via 'login: admin'). Do not specify 'login: required' since offline
  # requests (Cron, Task Queue, etc.) will fail with this error:
  #   Request failed because URL requires user login. For requests invoked
  #   within App Engine (offline requests like Task Queue, or webhooks like XMPP
  #   and Incoming Mail), the URL must require admin login (or no login)
  #login: admin
  #secure: always

# Currently supported libraries are documented by
# https://developers.google.com/appengine/docs/python/tools/libraries27
# Keep in sync with target_info.py library validation code.
libraries:
- name: django
  version: latest
- name: jinja2
  version: latest
- name: lxml
  version: latest
- name: markupsafe
  version: latest
- name: numpy
  version: latest
- name: PIL
  version: latest
- name: pycrypto
  version: latest
- name: setuptools
  version: latest
- name: webapp2
  version: latest
- name: webob
  version: latest
- name: yaml
  version: latest

skip_files:
# default list
- ^app\.ya?ml
- ^(.*/)?index\.ya?ml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.so










# things that don't need to be uploaded
- ^(.*/)?tests.*
- ^(.*/)?run_tests\.py
- ^(.*/)?README\.txt
